### PR TITLE
fix deprecated 'floor' operator

### PR DESCRIPTION
**Pull request by elijahrockers**
but still not concatentation operators. use 'collect' instead at

DCEMRI/src/validate.jl:19
DCEMRI/src/validate.jl:28
DCEMRI/src/validate.jl:61
DCEMRI/src/validate.jl:134
DCEMRI/src/validate.jl:135

### CODE REVIEW

**Comment by davidssmith** [comment]
Thanks!

**Comment by davidssmith** [comment]
Note that this won't appear in the official package until I bump the version number up in https://github.com/JuliaLang/METADATA.jl

**Comment by elijahrockers** [comment]
Sure.. just a heads up, I am new to git, but interested in getting to know it. Also brand new to Julia, so definitely make sure to review my pull requests

**Comment by elijahrockers** [comment]
quite familiar with MATLAB though, which I see some striking similarities with

**Pull request merged**
